site_name: Amp: Atomistic Machine-learning Potentials
pages:
- [index.rst, Home]
- [introduction.rst, Introduction]
- [installation.rst, Installation]
- [useamp.rst, How to use Amp?]
- [theory.rst, Theory]
- [parallelcomputing.rst, Parallel Computing]
theme: readthedocs
google_analytics: ['UA-54480782-1', 'auto']
